### PR TITLE
don't crash if field name is empty

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by Mic92** [comment]
also less code :)

**Comment by Mic92** [comment]
Now I can just do `export FOO=$(rbw get --field account-id myaccount)`.

**Comment by doy** [comment]
turns out there were a lot of places in `get_field` which were being handled pretty inconsistently - i went ahead and fixed them up more thoroughly in bb1791d14e64ad83fb57116a24eb913a4946afed. thanks!

**Comment by Mic92** [comment]
Thanks. Looking forward to a release.

**Pull request closed without merging**
