### PR TITLE
Pass `User-Agent` header to prevent login from returning 400

### LINKED ISSUE #145: "rbw login: failed to log in to bitwarden instance: Username or password is incorrect. Try again."
Today I noticed that I can no longer log in with rbw. It does not accept my password.

I noticed that others have reported this problem in #32 and #88, though originally those issues were filed for different problems, so I'm creating an issue for this specific problem. Hope this helps.

### PR DESCRIPTION
**Pull request by Ty3uK**
Fixes #145

### CODE REVIEW

**Comment by Ty3uK** [comment]
`cargo install --git https://github.com/Ty3uK/rbw --rev 40a33ec`

**Comment by Msouza91** [comment]
Uninstalled previous version and installed with the parameter listed, but I'm still getting the error, how can I provide useful debug info?

**Comment by mxkrsv** [comment]
> Uninstalled previous version and installed with the parameter listed, but I'm still getting the error, how can I provide useful debug info?

@Msouza91 you must `export PATH="$HOME/.cargo/bin:$PATH"`, otherwise the new `rbw` will launch the old `rbw-agent`, which is the reason of the failure.

**Comment by mxkrsv** [comment]
Worked for me, thank you very much!

**Comment by Msouza91** [comment]
> export PATH="$HOME/.cargo/bin:$PATH

I already had this on my .zshrc, not to mention that I uninstalled the previous version, did an rbw purge and deleted the config file before installing this rev to be on the safe side.

**Comment by rjc** [comment]
I can confirm this fixes the issue from #145.

**Comment by joelsleeba** [comment]
@Msouza91 I faced the same issue. Problem was that even after uninstallation, the old rbw-agent was running in the background. Kill rbw-agent. Try `rbw login` again.

**Comment by rpdelaney** [comment]
[Linter error](https://github.com/doy/rbw/actions/runs/7276592707/job/19826756934?pr=151):

```
 error: you seem to be trying to use `match` for destructuring a single pattern. Consider using `if let`
  --> src/edit.rs:35:29
   |
35 |               Some(editor) => match editor.to_str() {
   |  _____________________________^
36 | |                 Some("vim" | "nvim") => {
37 | |                     // disable swap files and viminfo for password entry
38 | |                     editor_args.push(std::ffi::OsString::from("-ni"));
...  |
43 | |                 }
44 | |             },
   | |_____________^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_match_else
   = note: `-D clippy::single-match-else` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::single_match_else)]`
help: try
   |
35 ~             Some(editor) => if let Some("vim" | "nvim") = editor.to_str() {
36 +                 // disable swap files and viminfo for password entry
37 +                 editor_args.push(std::ffi::OsString::from("-ni"));
38 +                 editor_args.push(std::ffi::OsString::from("NONE"));
39 +             } else {
40 +                 // other editor support welcomed
41 ~             },
   |
```

**Comment by Ty3uK** [comment]
> [Linter error](https://github.com/doy/rbw/actions/runs/7276592707/job/19826756934?pr=151):
> 
> 
> 
> ```
> 
>  error: you seem to be trying to use `match` for destructuring a single pattern. Consider using `if let`
> 
>   --> src/edit.rs:35:29
> 
>    |
> 
> 35 |               Some(editor) => match editor.to_str() {
> 
>    |  _____________________________^
> 
> 36 | |                 Some("vim" | "nvim") => {
> 
> 37 | |                     // disable swap files and viminfo for password entry
> 
> 38 | |                     editor_args.push(std::ffi::OsString::from("-ni"));
> 
> ...  |
> 
> 43 | |                 }
> 
> 44 | |             },
> 
>    | |_____________^
> 
>    |
> 
>    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_match_else
> 
>    = note: `-D clippy::single-match-else` implied by `-D warnings`
> 
>    = help: to override `-D warnings` add `#[allow(clippy::single_match_else)]`
> 
> help: try
> 
>    |
> 
> 35 ~             Some(editor) => if let Some("vim" | "nvim") = editor.to_str() {
> 
> 36 +                 // disable swap files and viminfo for password entry
> 
> 37 +                 editor_args.push(std::ffi::OsString::from("-ni"));
> 
> 38 +                 editor_args.push(std::ffi::OsString::from("NONE"));
> 
> 39 +             } else {
> 
> 40 +                 // other editor support welcomed
> 
> 41 ~             },
> 
>    |
> 
> ```

I know, I fixed this and got another linter error in another files.

I suppose we need to fix main and all PR's need to be rebased.

**Comment by rpdelaney** [comment]
[`main`](https://github.com/doy/rbw/commit/bb1791d14e64ad83fb57116a24eb913a4946afed) looks like it's building okay to me. 🤔 I'll take a stab at it.

**Comment by rjc** [comment]
Just an FYI - this fix has now been committed the [_-current_](https://marc.info/?m=170335547931438) and [_-stable_](https://marc.info/?m=170335569931508) branches of the OpenBSD's _ports_ tree.

Thank you!

**Comment by Ty3uK** [comment]
> [`main`](https://github.com/doy/rbw/commit/bb1791d14e64ad83fb57116a24eb913a4946afed) looks like it's building okay to me. 🤔 I'll take a stab at it.

I got this on fresh main:

```
❯ cargo clippy --all-targets -- -Dwarnings
    Checking rbw v1.8.3 (/Users/ty3uk/projects/rust/rbw)
error: you seem to be trying to use `match` for destructuring a single pattern. Consider using `if let`
  --> src/edit.rs:35:29
   |
35 |               Some(editor) => match editor.to_str() {
   |  _____________________________^
36 | |                 Some("vim" | "nvim") => {
37 | |                     // disable swap files and viminfo for password entry
38 | |                     editor_args.push(std::ffi::OsString::from("-ni"));
...  |
43 | |                 }
44 | |             },
   | |_____________^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_match_else
   = note: `-D clippy::single-match-else` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::single_match_else)]`
help: try
   |
35 ~             Some(editor) => if let Some("vim" | "nvim") = editor.to_str() {
36 +                 // disable swap files and viminfo for password entry
37 +                 editor_args.push(std::ffi::OsString::from("-ni"));
38 +                 editor_args.push(std::ffi::OsString::from("NONE"));
39 +             } else {
40 +                 // other editor support welcomed
41 ~             },
   |

error: could not compile `rbw` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `rbw` (lib test) due to previous error
```

**Comment by Msouza91** [comment]
If you look closely you may see that the 1.83 version mentioned

**Review by doy — APPROVED** [review]

**Pull request merged**
