### PR TITLE
Show type of custom field

### PR DESCRIPTION
**Pull request by fdw**
This adds some code to get the type of a custom field and to display it. However, some fine-tuning is probably necessary...

Issue: #67

### CODE REVIEW

**Comment by fdw** [comment]
Hey, are you still interested in this PR?

**Comment by fdw** [comment]
This PR is now about two years old, with no reaction from you, @doy. If you are interested in it, please tell me, otherwise I'll close the PR.

**Comment by doy** [comment]
sorry about that - i had assumed that it being in draft meant you were still working on it. honestly, i'd rather see this sort of functionality covered by the json output rather than include it in the default output, because it's not usually that relevant - is there something specific you're interested in here?

**Comment by fdw** [comment]
Including it in the JSON output would be fine for me too - I think this PR draft predates JSON 😉

However, it's not there yet, is it? Should I try to open a PR? (But be warned that I'd need some help.)

**Comment by doy** [comment]
i added this to the json output in 0942dde - if this works for you, i'd prefer this implementation, but let me know if there's some other functionality you'd like here.

**Comment by fdw** [comment]
Yes, looks good to me. Thank you!

**Pull request closed without merging**
