### PR TITLE
Implement argon2 kdf

### PR DESCRIPTION
**Pull request by quexten**
Hi,

this work-in-progress PR implements basic support for the argon2 KDF. Logging in with default (and at least one other non-default setting, I did not test the boundary values yet) already works.
I'm not super familiar with rust yet, so it might require another iteration.
Also, I still intend to replace the kdfType (currently has type u32) with an enum.

Nevertheless, I'm happy to get some feedback on this PR.

### CODE REVIEW

**Comment by quexten** [comment]
Ok, the type of the kdf is now an enum instead of u32.

I believe it is now ready for a review.

**Comment by doy** [comment]
sorry for not getting to this sooner - do you think you could use the [argon2](https://crates.io/crates/argon2) crate instead? i'm really trying to minimize the number of different cryptographic libraries i'm using here, and most of the rest of the code already uses rust-crypto.

**Comment by quexten** [comment]
Okay, I have changed to the rustcrypto package and re-based to the latest master branch to resolve merge conflicts.

**Comment by doy** [comment]
thanks!

**Pull request merged**
